version: "3"
services:
  web:
    image: "ghcr.io/visualize-admin/visualization-tool/visualization-tool:release"
    ports:
      - "3000:3000"
    restart: always
    environment: 
      DATABASE_URL: "postgres://postgres:password@db:5432/visualization_tool"
      ENDPOINT: "sparql+https://lindas.admin.ch/query"
      SPARQL_GEO_ENDPOINT: "https://geo.ld.admin.ch/query"
      GRAPHQL_ENDPOINT: "/api/graphql"
      WHITELISTED_DATA_SOURCES: '["Prod", "Int", "Test"]'
      NEXTAUTH_SECRET: "putSomeDummySecretHereToAvoidNastyWarnings=="
      NEXTAUTH_URL: "/api/auth/"
  db:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "password"
